# Generated by Django 3.2.23 on 2026-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_satker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sekretaris', 'Sekretaris'), ('kasubbag', 'Kasubbag'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='Role'),
        ),
    ]
