# Generated by Django 3.2.23 on 2026-04-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_subbagian'),
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_bagian',
            field=models.ForeignKey(blank=True, help_text='Sub Bagian tempat user bertugas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.subbagian', verbose_name='Sub Bagian'),
        ),
    ]
