# Generated by Django 3.2.23 on 2026-03-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_nomorsuratcounter_satker'),
        ('accounts', '0003_remove_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='satker',
            field=models.ForeignKey(blank=True, help_text='Satuan Kerja tempat user bertugas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.unitkerja', verbose_name='Satuan Kerja'),
        ),
    ]
