# Generated by Django 3.2.23 on 2026-03-17 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(help_text='Nomor ter-generate otomatis dari master', max_length=100, unique=True, verbose_name='Nomor Surat')),
                ('perihal', models.CharField(max_length=255, verbose_name='Perihal')),
                ('tanggal', models.DateField(verbose_name='Tanggal Surat')),
                ('tujuan', models.CharField(blank=True, max_length=255, verbose_name='Tujuan')),
                ('pengirim', models.CharField(blank=True, max_length=255, verbose_name='Pengirim')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surat_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh')),
                ('master_surat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.mastersurat', verbose_name='Kategori Surat')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Surat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuratAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='surat_attachments/%Y/%m/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Nama File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='surat.surat', verbose_name='Surat')),
            ],
            options={
                'verbose_name': 'Lampiran',
                'verbose_name_plural': 'Lampiran',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
