# Generated by Django 3.2.23 on 2026-03-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='kategori_surat',
            field=models.CharField(choices=[('urgensi', 'Urgensi'), ('terkini', 'Terkini')], default='urgensi', max_length=20, verbose_name='Kategori Surat'),
        ),
    ]
