# Generated by Django 3.2.23 on 2026-03-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0002_surat_kategori_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='kategori_surat',
            field=models.CharField(choices=[('urgensi', 'Urgensi'), ('terkini', 'Terkini')], default='terkini', max_length=20, verbose_name='Kategori Surat'),
        ),
        migrations.AlterField(
            model_name='surat',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Waiting For Approval'), ('approved', 'Approved'), ('inprogress', 'Inprogress'), ('done', 'Done'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
