# Generated by Django 3.2.23 on 2026-03-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_cleanup_unused_models'),
        ('surat', '0003_remove_surat_master_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='klasifikasi',
            field=models.ForeignKey(blank=True, help_text='Kode klasifikasi arsip sesuai substansi surat', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.klasifikasiarsip', verbose_name='Klasifikasi Arsip'),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(help_text='Nomor ter-generate otomatis saat surat dibuat', max_length=100, unique=True, verbose_name='Nomor Surat'),
        ),
    ]
