# Generated by Django 3.2.23 on 2026-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0003_auto_20260330_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Waiting For Kasubbag Approval'), ('approved_kasubbag', 'Approved Kasubbag'), ('approved', 'Approved Sekretaris'), ('inprogress', 'Inprogress'), ('done', 'Done'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
