# Generated by Django 3.2.23 on 2026-04-02 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surat', '0004_alter_surat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(help_text='Nomor surat tercetak dari instansi pengirim', max_length=100, verbose_name='Nomor Surat')),
                ('pengirim', models.CharField(help_text='Asal instansi pengirim surat', max_length=255, verbose_name='Pengirim')),
                ('perihal', models.CharField(max_length=255, verbose_name='Perihal')),
                ('lampiran_surat', models.FileField(blank=True, help_text='Wajib diisi saat mengubah status ke Inprogress', null=True, upload_to='surat_masuk/%Y/%m/', verbose_name='Lampiran Surat (Scan PDF)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('inprogress', 'Inprogress (Disposisi)'), ('done', 'Done')], default='draft', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, help_text='Alasan/Keterangan saat disposisi selesai ditindaklanjuti', verbose_name='Catatan Tindak Lanjut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surat_masuk_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh')),
                ('disposisi', models.ForeignKey(help_text='Penerima disposisi (Kasubbag / Sekretaris)', on_delete=django.db.models.deletion.PROTECT, related_name='disposisi_surat_masuk', to=settings.AUTH_USER_MODEL, verbose_name='Disposisi Ke')),
            ],
            options={
                'verbose_name': 'Surat Masuk',
                'verbose_name_plural': 'Surat Masuk',
                'ordering': ['-created_at'],
            },
        ),
    ]
