# Generated by Django 3.2.23 on 2026-04-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_subbagian'),
        ('surat', '0005_suratmasuk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='tujuan',
        ),
        migrations.AddField(
            model_name='surat',
            name='penerima',
            field=models.CharField(blank=True, max_length=255, verbose_name='Penerima'),
        ),
        migrations.AddField(
            model_name='surat',
            name='sub_bagian',
            field=models.ForeignKey(blank=True, help_text='Sub Bagian yang terkait', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.subbagian', verbose_name='Sub Bagian'),
        ),
        migrations.AddField(
            model_name='surat',
            name='tujuan_surat',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Tujuan surat: Internal atau External', max_length=20, verbose_name='Tujuan Surat'),
        ),
    ]
