# Generated by Django 3.2.23 on 2026-04-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0006_auto_20260407_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='tujuan_surat',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', help_text='Tujuan surat: Internal atau External', max_length=20, verbose_name='Tujuan Surat'),
        ),
    ]
