# Generated by Django 3.2.25 on 2026-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0007_alter_surat_tujuan_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='is_backdate',
            field=models.BooleanField(default=False, help_text='Menandakan surat di-backdate ke tanggal sebelumnya', verbose_name='Surat Backdate'),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(help_text='Nomor ter-generate otomatis saat surat dibuat', max_length=100, verbose_name='Nomor Surat'),
        ),
    ]
