"""
Surat (document) models with auto-generated numbering and file attachments.

Surat references JenisNaskahDinas and KlasifikasiArsip directly.
The nomor_surat is auto-generated based on these references plus the
user's SATKER code.
"""

from django.conf import settings
from django.db import models


class Surat(models.Model):
    """
    Main document model representing a letter/surat.

    The nomor_surat is auto-generated when the record is created,
    based on jenis_naskah, klasifikasi, and the user's SATKER.
    Format: {NO}/{KLASIFIKASI}-{JENIS}/{SATKER}/{TAHUN}
    """

    class Status(models.TextChoices):
        """Document lifecycle status."""
        DRAFT = 'draft', 'Draft'
        SUBMITTED = 'submitted', 'Waiting For Kasubbag Approval'
        APPROVED_KASUBBAG = 'approved_kasubbag', 'Approved Kasubbag'
        APPROVED = 'approved', 'Approved Sekretaris'
        INPROGRESS = 'inprogress', 'Inprogress'
        DONE = 'done', 'Done'
        REJECTED = 'rejected', 'Ditolak'

    nomor_surat = models.CharField(
        max_length=100,
        unique=True,
        verbose_name='Nomor Surat',
        help_text='Nomor ter-generate otomatis saat surat dibuat',
    )
    jenis_naskah = models.ForeignKey(
        'master.JenisNaskahDinas',
        on_delete=models.PROTECT,
        verbose_name='Jenis Naskah Dinas',
        null=True,
        blank=True,
    )
    klasifikasi = models.ForeignKey(
        'master.KlasifikasiArsip',
        on_delete=models.PROTECT,
        verbose_name='Klasifikasi Arsip',
        help_text='Kode klasifikasi arsip sesuai substansi surat',
        null=True,
        blank=True,
    )
    perihal = models.CharField(max_length=255, verbose_name='Perihal')
    tanggal = models.DateField(verbose_name='Tanggal Surat')
    penerima = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='Penerima',
    )
    pengirim = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='Pengirim',
    )
    sub_bagian = models.ForeignKey(
        'master.SubBagian',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Sub Bagian',
        help_text='Sub Bagian yang terkait',
    )
    tujuan_surat = models.CharField(
        max_length=20,
        choices=[('internal', 'Internal'), ('external', 'External')],
        default='external',
        verbose_name='Tujuan Surat',
        help_text='Tujuan surat: Internal atau External',
    )
    kategori_surat = models.CharField(
        max_length=20,
        choices=[('urgensi', 'Urgensi'), ('terkini', 'Terkini')],
        default='terkini',
        verbose_name='Kategori Surat',
    )
    notes = models.TextField(blank=True, verbose_name='Catatan')
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name='Status',
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='surat_created',
        verbose_name='Dibuat oleh',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Surat'
        verbose_name_plural = 'Surat'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.nomor_surat} — {self.perihal}"

    @property
    def is_editable(self):
        """Check if the document can still be edited."""
        return self.status in [self.Status.DRAFT, self.Status.INPROGRESS]

    @property
    def status_color(self):
        """Return a CSS color class for the current status."""
        colors = {
            self.Status.DRAFT: 'secondary',
            self.Status.SUBMITTED: 'warning',
            self.Status.APPROVED_KASUBBAG: 'info',
            self.Status.APPROVED: 'success',
            self.Status.INPROGRESS: 'info',
            self.Status.DONE: 'success',
            self.Status.REJECTED: 'danger',
        }
        return colors.get(self.status, 'secondary')


class SuratAttachment(models.Model):
    """File attachment linked to a Surat."""

    surat = models.ForeignKey(
        Surat,
        on_delete=models.CASCADE,
        related_name='attachments',
        verbose_name='Surat',
    )
    file = models.FileField(
        upload_to='surat_attachments/%Y/%m/',
        verbose_name='File',
    )
    filename = models.CharField(max_length=255, verbose_name='Nama File')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Lampiran'
        verbose_name_plural = 'Lampiran'
        ordering = ['-uploaded_at']

    def __str__(self):
        return self.filename


class SuratMasuk(models.Model):
    """
    Model for incoming mail (Surat Masuk) where its number is generated by an external party,
    and it follows a different lifecycle (Draft -> Inprogress (Disposisi) -> Done (Tindak Lanjut)).
    """

    class Status(models.TextChoices):
        """Document lifecycle status."""
        DRAFT = 'draft', 'Draft'
        INPROGRESS = 'inprogress', 'Inprogress (Disposisi)'
        DONE = 'done', 'Done'

    nomor_surat = models.CharField(
        max_length=100,
        verbose_name='Nomor Surat',
        help_text='Nomor surat tercetak dari instansi pengirim',
    )
    pengirim = models.CharField(
        max_length=255,
        verbose_name='Pengirim',
        help_text='Asal instansi pengirim surat',
    )
    perihal = models.CharField(max_length=255, verbose_name='Perihal')
    disposisi = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='disposisi_surat_masuk',
        verbose_name='Disposisi Ke',
        help_text='Penerima disposisi (Kasubbag / Sekretaris)',
    )
    lampiran_surat = models.FileField(
        upload_to='surat_masuk/%Y/%m/',
        blank=True,
        null=True,
        verbose_name='Lampiran Surat (Scan PDF)',
        help_text='Wajib diisi saat mengubah status ke Inprogress',
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name='Status',
    )
    catatan = models.TextField(
        blank=True,
        verbose_name='Catatan Tindak Lanjut',
        help_text='Alasan/Keterangan saat disposisi selesai ditindaklanjuti',
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='surat_masuk_created',
        verbose_name='Dibuat oleh',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Surat Masuk'
        verbose_name_plural = 'Surat Masuk'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.nomor_surat} — {self.pengirim}"

    @property
    def status_color(self):
        """Return a CSS color class for the current status."""
        colors = {
            self.Status.DRAFT: 'secondary',
            self.Status.INPROGRESS: 'warning',
            self.Status.DONE: 'success',
        }
        return colors.get(self.status, 'secondary')
