# Generated by Django 3.2.23 on 2026-03-17 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Diajukan'), ('approve', 'Disetujui'), ('reject', 'Ditolak'), ('revise', 'Direvisi')], max_length=20, verbose_name='Aksi')),
                ('comment', models.TextField(blank=True, verbose_name='Komentar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='surat.surat', verbose_name='Surat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Riwayat Approval',
                'verbose_name_plural': 'Riwayat Approval',
                'ordering': ['-timestamp'],
            },
        ),
    ]
