# Generated by Django 3.2.23 on 2026-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('submit', 'Diajukan'), ('inprogress', 'Ditindaklanjuti'), ('approve', 'Disetujui'), ('reject', 'Ditolak'), ('revise', 'Direvisi')], max_length=20, verbose_name='Aksi'),
        ),
    ]
