# Generated by Django 3.2.23 on 2026-03-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('code', models.CharField(help_text='Kode singkat departemen, contoh: HRD, FIN, IT', max_length=10, unique=True, verbose_name='Kode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Surat Keluar Umum, SK Internal', max_length=100, verbose_name='Nama Kategori Surat')),
                ('prefix', models.CharField(help_text='Contoh: SKU, SKI, MEMO', max_length=20, verbose_name='Prefix')),
                ('format_template', models.CharField(default='{PREFIX}/{NO}/{BULAN_ROMAWI}/{TAHUN}', help_text='Gunakan placeholder: {PREFIX}, {NO}, {BULAN_ROMAWI}, {BULAN}, {TAHUN}, {DEPT}', max_length=100, verbose_name='Format Nomor')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Nomor Terakhir')),
                ('last_reset_year', models.PositiveIntegerField(default=0, verbose_name='Tahun Reset Terakhir')),
                ('last_reset_month', models.PositiveIntegerField(default=0, verbose_name='Bulan Reset Terakhir')),
                ('reset_period', models.CharField(choices=[('yearly', 'Tahunan'), ('monthly', 'Bulanan'), ('never', 'Tidak Reset')], default='yearly', max_length=10, verbose_name='Reset Counter')),
                ('padding', models.PositiveIntegerField(default=3, help_text='Jumlah digit minimum nomor urut (contoh: 3 → 001)', verbose_name='Digit Padding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.departemen', verbose_name='Departemen')),
            ],
            options={
                'verbose_name': 'Master Surat',
                'verbose_name_plural': 'Master Surat',
                'ordering': ['name'],
            },
        ),
    ]
