# Generated by Django 3.2.23 on 2026-03-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiArsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: PP, PP.01, PP.01.1', max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('jenis', models.CharField(choices=[('substantif', 'Substantif'), ('fasilitatif', 'Fasilitatif')], max_length=15, verbose_name='Jenis Klasifikasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.klasifikasiarsip', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Klasifikasi Arsip',
                'verbose_name_plural': 'Klasifikasi Arsip',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='JenisNaskahDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: SD, ND, ST', max_length=10, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Naskah Dinas',
                'verbose_name_plural': 'Jenis Naskah Dinas',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 01, 1, 1.1', max_length=10, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 11 (Aceh), 1101 (Kab. Aceh Selatan)', max_length=10, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('level', models.CharField(choices=[('provinsi', 'Provinsi'), ('kabupaten_kota', 'Kabupaten/Kota')], max_length=20, verbose_name='Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.wilayah', verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='NomorSuratCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Nomor Terakhir')),
                ('jenis_naskah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.jenisnaskahdinas', verbose_name='Jenis Naskah Dinas')),
                ('satker', models.ForeignKey(blank=True, help_text='Null = KPU Pusat', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.unitkerja', verbose_name='Satuan Kerja')),
            ],
            options={
                'verbose_name': 'Counter Nomor Surat',
                'verbose_name_plural': 'Counter Nomor Surat',
                'ordering': ['-tahun', 'jenis_naskah'],
            },
        ),
    ]
