# Generated by Django 3.2.23 on 2026-03-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomorsuratcounter',
            unique_together={('jenis_naskah', 'satker', 'tahun')},
        ),
    ]
