# Generated by Django 3.2.23 on 2026-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_nomorsuratcounter_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 1, 2, 3, 4', max_length=10, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub Bagian',
                'verbose_name_plural': 'Sub Bagian',
                'ordering': ['kode'],
            },
        ),
    ]
