# Generated by Django 3.2.23 on 2026-03-25 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisNaskahDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: SD, ND, ST', max_length=10, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('kategori', models.CharField(choices=[('arahan_pengaturan', 'Arahan - Pengaturan'), ('arahan_penetapan', 'Arahan - Penetapan'), ('penugasan', 'Arahan - Penugasan'), ('korespondensi', 'Korespondensi'), ('khusus', 'Khusus')], max_length=25, verbose_name='Kategori')),
                ('uses_klasifikasi_code', models.BooleanField(default=True, help_text='Jika False, penomoran menggunakan format sederhana (Nomor X Tahun YYYY). Berlaku untuk Peraturan & Keputusan.', verbose_name='Gunakan Kode Klasifikasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Naskah Dinas',
                'verbose_name_plural': 'Jenis Naskah Dinas',
                'ordering': ['kategori', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='PejabatPenandatangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: K, S, D, IR, Sek-Prov', max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pejabat Penandatangan',
                'verbose_name_plural': 'Pejabat Penandatangan',
                'ordering': ['kode'],
            },
        ),
        migrations.RemoveField(
            model_name='mastersurat',
            name='departemen',
        ),
        migrations.RemoveField(
            model_name='mastersurat',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='mastersurat',
            name='format_template',
            field=models.CharField(default='{NO}/{KLASIFIKASI}-{JENIS}/{UNIT}/{TAHUN}', help_text='Placeholder: {NO}, {KLASIFIKASI}, {JENIS}, {UNIT}, {TAHUN}, {PEJABAT}, {WILAYAH}', max_length=150, verbose_name='Format Nomor'),
        ),
        migrations.AlterField(
            model_name='mastersurat',
            name='name',
            field=models.CharField(help_text='Contoh: Surat Dinas Biro Hukum, Nota Dinas Ketua KPU', max_length=100, verbose_name='Nama Konfigurasi'),
        ),
        migrations.AlterField(
            model_name='mastersurat',
            name='padding',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah digit minimum nomor urut (contoh: 1 → 1, 3 → 001)', verbose_name='Digit Padding'),
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 11 (Aceh), 1101 (Kab. Aceh Selatan)', max_length=10, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('level', models.CharField(choices=[('provinsi', 'Provinsi'), ('kabupaten_kota', 'Kabupaten/Kota')], max_length=20, verbose_name='Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.wilayah', verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 01, 1, 1.1', max_length=10, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('level', models.CharField(choices=[('biro', 'Biro / Inspektorat / Pusat'), ('bagian', 'Bagian'), ('subbagian', 'Subbagian')], max_length=15, verbose_name='Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.unitkerja', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['kode'],
                'unique_together': {('kode', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='KlasifikasiArsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: PP, PP.01, PP.01.1', max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('jenis', models.CharField(choices=[('substantif', 'Substantif'), ('fasilitatif', 'Fasilitatif')], max_length=15, verbose_name='Jenis Klasifikasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.klasifikasiarsip', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Klasifikasi Arsip',
                'verbose_name_plural': 'Klasifikasi Arsip',
                'ordering': ['kode'],
            },
        ),
        migrations.AddField(
            model_name='mastersurat',
            name='jenis_naskah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='master.jenisnaskahdinas', verbose_name='Jenis Naskah Dinas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersurat',
            name='klasifikasi',
            field=models.ForeignKey(default=1, help_text='Kode klasifikasi arsip sesuai substansi surat', on_delete=django.db.models.deletion.PROTECT, to='master.klasifikasiarsip', verbose_name='Klasifikasi Arsip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersurat',
            name='pejabat',
            field=models.ForeignKey(blank=True, help_text='Khusus Nota Dinas, Memorandum, dan Lembar Disposisi', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.pejabatpenandatangan', verbose_name='Pejabat Penandatangan'),
        ),
        migrations.AddField(
            model_name='mastersurat',
            name='unit_kerja',
            field=models.ForeignKey(blank=True, help_text='Biro/Inspektorat/Pusat pembuat naskah dinas', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.unitkerja', verbose_name='Unit Kerja'),
        ),
        migrations.AddField(
            model_name='mastersurat',
            name='wilayah',
            field=models.ForeignKey(blank=True, help_text='Diisi untuk KPU Provinsi atau KPU Kabupaten/Kota', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.wilayah', verbose_name='Wilayah'),
        ),
    ]
