# Generated by Django 3.2.23 on 2026-04-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_subbagian'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomorsuratcounter',
            name='sub_bagian',
            field=models.ForeignKey(blank=True, help_text='Null = External letter', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.subbagian', verbose_name='Sub Bagian'),
        ),
        migrations.AlterUniqueTogether(
            name='nomorsuratcounter',
            unique_together={('jenis_naskah', 'satker', 'sub_bagian', 'tahun')},
        ),
    ]
