# Generated by Django 3.2.23 on 2026-03-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_remove_jenisnaskahdinas_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenisnaskahdinas',
            options={'ordering': ['kode'], 'verbose_name': 'Jenis Naskah Dinas', 'verbose_name_plural': 'Jenis Naskah Dinas'},
        ),
    ]
