# Generated by Django 3.2.23 on 2026-03-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_jenisnaskahdinas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomorsuratcounter',
            name='satker',
            field=models.ForeignKey(blank=True, help_text='Null = KPU Pusat', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.unitkerja', verbose_name='Satuan Kerja'),
        ),
    ]
